version: '3.9'
services:
  react-vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
      - ./index.html:/app/index.html
