version: "3.9"
services:
  react-vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/www/pre-recover/.well-known:/var/www/pre-recover/.well-known"
      - "/etc/letsencrypt/live/pre-recover.com/fullchain.pem:/etc/letsencrypt/live/pre-recover.com/fullchain.pem"
      - "/etc/letsencrypt/live/pre-recover.com/privkey.pem:/etc/letsencrypt/live/pre-recover.com/privkey.pem"
