export type Doctor = {
  address: string;
  center: number;
  city: number;
  clinic: null;
  country: number;
  created_at: Date;
  email: string | null;
  email_verification_code: number;
  image: string;
  first_name: string;
  id: number;
  last_login: Date | null;
  last_name: string;
  middle_name: string;
  number: string;
  password: string;
  registration_date: Date;
  reset_code: number;
  review_date: null;
  review_passed: null;
  specialization: string;
  updated_at: Date;
  verification_code: number;
  work_experience: string;
};
