name: Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: remote ssh rebuild
        uses: appleboy/ssh-action@master
        with:
          host: ${{  secrets.SSH_HOST  }}
          username: ${{  secrets.SSH_USER}}
          key: ${{  secrets.SSH_KEY}}
          script:  | 
                  bash build.sh